import matplotlib.pyplot as plt
import numpy as np

# Define the sequences
human_seq = "GAGCAGGTGCAGTGACGAGTCCCGGCCTGCGGCGCGACCTGCGCCCTGGGCGGGCGCGGTCCCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCCCTGGCCCTAGGCATCGCCCTGGACCGCCACTTGCGCAGCCCACCTGCTGGCTGCTTCTTCCTAAGCCTACTACTAGCCGGGCTGCTCACAGGGCTGGCACTGCCCATGCTGCCTGGGCTATGGAGCCGGAACCATCAGGGCTACTGGTCCTGCCTCCTTCTCCACTTGACCCCCAACTTTTGTTTCCTTTCCCTGCTTGCCAATCTGCTGCTGGTGCATGGGGAACGCTACATGGCAGTGTTGCAGCCACTCCGGCCCCATGGAAGTGTGCGGCTAGCCCTGTTCCTCACCTGGGTCAGCTCCCTGTTCTTTGCCAGCCTGCCTGCTCTGGGCTGGAACCATTGGAGCCCTGATGCCAACTGCAGCTCCCAAGCTGTCTTCCCAGCCCCCTACCTCTACCTGGAAGTTTATGGCCTCCTGTTGCCTGCCGTGGGGGCCACTGCCCTTCTCTCTGTCCGCGTGTTGGCCACTGCCCACCGCCAGCTGTGTGAGATCCGCCGACTGGAGCGGGCAGTGTGCCGCGATGTACTCAACCCTGGCTAGGGCTCTCACCTGGAGGCAGGCTAGGGCACAGGCAGGAGCCACACTGCTCTTCTTGCTGTGTTGGGGGCCCTATGTGGCCACATTGCTCCTGTCAGTCTTGGCCTATGAGCGTCGCCCACCACTAGGGCCTGGAACTCTGTTATCGCTCATCTCATTGGGCAGCACCAGTGCTGCCGCTGTGCCTGTGGCCATGGGGCTGGGTGATCAGCGCTACACAGCCCCCTGGAGGACAGCTGCCCAAAGGTGTCTACGAGTGCTTCGAGGAAGAGCCAAGAGGGACAATCCAGGCCCCAGCACTGCCTACCACACCAGTAGCCAATGCAGCATTGACCTGGACTTGAATTAGA"
pig_seq = "ATGATGACACCCAACAGCACTGAGCTGTCGGCCATTCCCATGGGGGTTCTGGGGCTTTCCTTGGCCCTGGCAAGCCTCATCGTCATCGCCAACCTGCTCCTGGCCCTAGGCATCGCCCTGGACCGCCACTTGCGCAGCCCACCTGCTGGCTGCTTCTTCCTAAGCCTACTACTAGCCGGGCTGCTCACAGGGCTGGCACTGCCCATGCTGCCTGGGCTATGGAGCCGGAACCATCAGGGCTACTGGTCCTGCCTCCTTCTCCACTTGACCCCCAACTTTTGTTTCCTTTCCCTGCTTGCCAATCTGCTGCTGGTGCATGGGGAACGCTACATGGCAGTGTTGCAGCCACTCCGGCCCCATGGAAGTGTGCGGCTAGCCCTGTTCCTCACCTGGGTCAGCTCCCTGTTCTTTGCCAGCCTGCCTGCTCTGGGCTGGAACCATTGGAGCCCTGATGCCAACTGCAGCTCCCAAGCTGTCTTCCCAGCCCCCTACCTCTACCTGGAAGTTTATGGCCTCCTGTTGCCTGCCGTGGGGGCCACTGCCCTTCTCTCTGTCCGCGTGTTGGCCACTGCCCACCGCCAGCTGTGTGAGATCCGCCGACTGGAGCGGGCAGTGTGCCGCGATGTACTCAACCCTGGCTAGGGCTCTCACCTGGAGGCAGGCTAGGGCACAGGCAGGAGCCACACTGCTCTTCTTGCTGTGTTGGGGGCCCTATGTGGCCACATTGCTCCTGTCAGTCTTGGCCTATGAGCGTCGCCCACCACTAGGGCCTGGAACTCTGTTATCGCTCATCTCATTGGGCAGCACCAGTGCTGCCGCTGTGCCTGTGGCCATGGGGCTGGGTGATCAGCGCTACACAGCCCCCTGGAGGACAGCTGCCCAAAGGTGTCTACGAGTGCTTCGAGGAAGAGCCAAGAGGGACAATCCAGGCCCCAGCACTGCCTACCACACCAGTAGCCAATGCAGCATTGACCTGGACTTGAATTAG"

# Define the length of the sequences
len_human = len(human_seq)
len_pig = len(pig_seq)

# Define the size of the dot plot matrix
matrix = np.zeros((len(human_seq)+1,len(pig_seq)+1))


# Fill the dot plot matrix
for i in range(1, len_human +1 ):
    for j in range(1, len_pig +1 ):
        if human_seq[i - 1] == pig_seq[j - 1]:
            matrix[i][j] = 1

# Create the dot plot
fig, ax = plt.subplots()
ax.matshow(matrix, cmap='Greys')

# Add axis labels
ax.set_xticks(range(len_pig + 1))
ax.set_yticks(range(len_human + 1))
ax.set_xticklabels(['Rat Sequence'] + list(pig_seq))
ax.set_yticklabels(['Human Sequence'] + list(human_seq))

# Add title
ax.set_title("Dot Plot of GPCR Sequences for Humans and Rat")

# Show the plot
plt.show()